# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "68fe182a0816d1eda4df4746c622b785"
name = "Payment-restriction"
handle = "payment-restriction"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_delivery_customizations,read_payment_customizations,write_discounts,write_payment_customizations"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
